# Generated by Django 5.2.8 on 2025-11-30 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_custom_design',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='cake_flavor',
            field=models.CharField(blank=True, choices=[('black_forest', 'Black Forest Cake'), ('chocolate', 'Chocolate Cake'), ('white_forest', 'White Forest Cake'), ('butter_scotch', 'Butter Scotch Cake'), ('red_velvet', 'Red Velvet Cake')], max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='is_cake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='max_tiers',
            field=models.IntegerField(choices=[(1, 'Single Tier'), (2, 'Two Tiers'), (3, 'Three Tiers')], default=1),
        ),
        migrations.CreateModel(
            name='CakeDesignReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cake_designs/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_references', to='products.product')),
            ],
        ),
    ]
