# Generated by Django 5.2.8 on 2025-12-02 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_allow_custom_design_product_cake_flavor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cakedesignreference',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['display_order', 'created_at']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='cake_flavor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='cakedesignreference',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cakedesignreference',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cakedesignreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='allow_reference_image',
            field=models.BooleanField(default=True, help_text='Allow customers to upload reference images'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_flavors',
            field=models.CharField(blank=True, help_text='Comma-separated list of available flavors', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base price for single tier', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='serves',
            field=models.CharField(blank=True, help_text='e.g., 4-6 people, 8-10 people', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, help_text='Short description for product cards', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, help_text='e.g., 500g, 1kg, 2kg', max_length=50),
        ),
        migrations.AddField(
            model_name='productimage',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cakedesignreference',
            name='image',
            field=models.ImageField(upload_to='cake_designs/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Detailed description for product detail page'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/%Y/%m/%d/'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['available', 'is_featured'], name='products_pr_availab_04d7a5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'available'], name='products_pr_categor_d726ba_idx'),
        ),
    ]
