# Generated by Django 5.2.8 on 2025-12-02 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_cakedesignreference_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='serves',
        ),
        migrations.AddField(
            model_name='product',
            name='cake_weight',
            field=models.CharField(blank=True, choices=[('0.5', '0.5 lb'), ('1', '1 lb'), ('2', '2 lb'), ('3', '3 lb'), ('4', '4 lb'), ('5', '5 lb'), ('custom', 'Custom Weight')], help_text='Weight in pounds (for cakes only)', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, help_text='e.g., 500g, 1kg, 2kg (for non-cake products)', max_length=50),
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField(help_text='Main product overview/description')),
                ('ingredients', models.TextField(blank=True, help_text='List of ingredients')),
                ('storage_instructions', models.TextField(blank=True, help_text='Storage and handling instructions')),
                ('allergy_info', models.TextField(blank=True, help_text='Allergy information')),
                ('cake_specific_info', models.TextField(blank=True, help_text='Cake-specific information (baking time, shelf life, etc.)')),
                ('customization_options', models.TextField(blank=True, help_text='Available customization options')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_description', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Detailed Description',
                'verbose_name_plural': 'Product Detailed Descriptions',
            },
        ),
    ]
