# Generated by Django 5.2.6 on 2026-02-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_image_product_image_2_product_image_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Available stock quantity. Set to 0 for unlimited stock (cakes/custom orders)'),
        ),
    ]
