# Generated by Django 5.2.8 on 2025-12-02 17:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0005_delete_cakedesignreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CakeDesignReference',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Reference image for cake design', upload_to='cake_designs/%Y/%m/%d/')),
                ('title', models.CharField(blank=True, help_text='Title/name for this design reference', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the desired design')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cake Design Reference',
                'verbose_name_plural': 'Cake Design References',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('online', 'Online Payment'), ('card', 'Credit/Debit Card')], default='cod', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cake_custom_flavor',
            field=models.CharField(blank=True, help_text="If flavor is 'custom'", max_length=200),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cake_custom_weight',
            field=models.CharField(blank=True, help_text="If weight is 'custom'", max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cake_flavor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cake_tiers',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cake_weight',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='message_on_cake',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='special_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product'], name='orders_orde_order_i_52f79a_idx'),
        ),
        migrations.AddField(
            model_name='cakedesignreference',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Parent order for this design reference', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='design_references', to='orders.order'),
        ),
        migrations.AddField(
            model_name='cakedesignreference',
            name='order_item',
            field=models.ForeignKey(blank=True, help_text='Specific order item (cake) for this design', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='design_references', to='orders.orderitem'),
        ),
        migrations.AddIndex(
            model_name='cakedesignreference',
            index=models.Index(fields=['order', 'order_item'], name='orders_cake_order_i_5dd4e8_idx'),
        ),
        migrations.AddIndex(
            model_name='cakedesignreference',
            index=models.Index(fields=['uploaded_at'], name='orders_cake_uploade_51c8ca_idx'),
        ),
    ]
