# Generated by Django 5.2.8 on 2026-01-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_unique_together_and_more'),
        ('orders', '0008_cakecustomization'),
        ('products', '0005_delete_cakedesignreference'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('cake_customization__isnull', False)), fields=('cart', 'product', 'cake_customization'), name='unique_cart_product_customization'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('cake_customization__isnull', True)), fields=('cart', 'product'), name='unique_cart_product'),
        ),
    ]
