# Generated by Django 5.2.6 on 2026-01-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_bakeryadmin_owner_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='delivery_address',
            field=models.TextField(blank=True, help_text='Default delivery address for customers', verbose_name='delivery address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Required. Enter a valid email address.', max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
