# Generated by Django 5.2.6 on 2026-01-22 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_delivery_address_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='RememberMeToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remember_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remember Me Token',
                'verbose_name_plural': 'Remember Me Tokens',
                'indexes': [models.Index(fields=['token'], name='users_remem_token_3b0d6a_idx'), models.Index(fields=['user', 'expires_at'], name='users_remem_user_id_7eac3d_idx')],
            },
        ),
    ]
