# Generated by Django 5.2.8 on 2026-01-06 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_payment_status'),
        ('payment', '0003_paymenttransaction_payment_pay_user_id_ca2927_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='orders.order'),
            preserve_default=False,
        ),
    ]
